// This file touches types that live in TeamService's aliased assembly (see the
// .csproj comment on the TeamService ProjectReference for why the alias exists).
extern alias TeamServiceAssembly;

namespace UMBRAL_Back_end.IntegrationTests.Teams;

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;
using UMBRAL_Back_end.IntegrationTests.Infrastructure;
using TeamServiceAssembly::TeamService.Adapter.Controllers;
using TeamServiceAssembly::TeamService.Application.Teams.Commands.CreateTeam;
using TeamServiceAssembly::TeamService.Domain.Teams;
using TeamServiceAssembly::TeamService.Infrastructure.Persistence;
using Xunit;

[Collection(TeamServiceCollection.Name)]
public class TeamPersistenceTests(TeamServicePostgresFixture fixture)
{
    [Fact]
    public async Task CreateTeam_ValidRequestThroughHttp_PersistsInRealPostgres()
    {
        var client = fixture.Factory.CreateClient();
        var sessionId = Guid.NewGuid();
        var request = new CreateTeamRequest(sessionId, $"Equipo Alfa {Guid.NewGuid()}");

        var response = await client.PostAsJsonAsync("/api/teams", request);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        // The controller serializes with ASP.NET's default (camelCase) JSON options;
        // match case-insensitively so this test doesn't depend on that detail.
        var body = await response.Content.ReadFromJsonAsync<CreateTeamResult>(
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        body.Should().NotBeNull();

        using var scope = fixture.Factory.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<TeamsDbContext>();
        var persisted = await dbContext.Teams.SingleAsync(t => t.Id == body!.TeamId);

        persisted.SessionId.Should().Be(sessionId);
        persisted.Name.Should().Be(request.TeamName);
        persisted.InviteCode.Should().Be(body!.InviteCode);
        persisted.MemberCount.Should().Be(1);
    }

    [Fact]
    public async Task SaveChanges_DuplicateInviteCode_ThrowsDueToUniqueIndexInPostgres()
    {
        using var scope = fixture.Factory.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<TeamsDbContext>();

        var sessionId = Guid.NewGuid();
        var first = Team.Create(sessionId, TeamName.Create("Equipo Uno").Value);
        var second = Team.Create(sessionId, TeamName.Create("Equipo Dos").Value);

        dbContext.Teams.Add(first);
        await dbContext.SaveChangesAsync();

        dbContext.Teams.Add(second);
        // InviteCode is randomly generated by the domain (TeamCode.Generate()) and has
        // no public setter, so force a real collision the way production could see one
        // (astronomically unlikely, but the unique index is the actual safety net) via
        // EF's property-entry access, which reaches the private setter directly.
        dbContext.Entry(second).Property(nameof(Team.InviteCode)).CurrentValue = first.InviteCode;

        var act = async () => await dbContext.SaveChangesAsync();

        await act.Should().ThrowAsync<DbUpdateException>();
    }

    [Fact]
    public async Task SaveChanges_InviteCodeLongerThanColumnLimit_ThrowsDueToVarcharLengthInPostgres()
    {
        using var scope = fixture.Factory.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<TeamsDbContext>();

        var oversizedInviteCode = new string('A', 11); // column is varchar(10)
        var id = Guid.NewGuid();

        var act = async () => await dbContext.Database.ExecuteSqlInterpolatedAsync(
            $"""
             INSERT INTO "Teams"
                 ("Id", "SessionId", "Name", "InviteCode", "MemberCount", "IsConnected",
                  "CurrentStageOrder", "CluesReceivedCurrentStage", "TotalCluesReceived",
                  "Score", "LastClueWasAutomatic", "WrongAttemptsCurrentStage")
             VALUES
                 ({id}, {Guid.NewGuid()}, 'Equipo Sobredimensionado', {oversizedInviteCode}, 1, false,
                  0, 0, 0, 0, false, 0)
             """);

        (await act.Should().ThrowAsync<PostgresException>())
            .Which.SqlState.Should().Be("22001");
    }

    [Fact]
    public async Task Database_Migrate_AppliesAllMigrationsCleanlyAndIsIdempotent()
    {
        using var scope = fixture.Factory.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<TeamsDbContext>();

        var pendingBeforeReRun = await dbContext.Database.GetPendingMigrationsAsync();
        pendingBeforeReRun.Should().BeEmpty();

        var appliedMigrations = await dbContext.Database.GetAppliedMigrationsAsync();
        var allMigrations = dbContext.Database.GetMigrations();
        appliedMigrations.Should().BeEquivalentTo(allMigrations);

        var act = async () => await dbContext.Database.MigrateAsync();
        await act.Should().NotThrowAsync();

        (await dbContext.Database.GetPendingMigrationsAsync()).Should().BeEmpty();
    }
}
