// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UMBRAL_Back_end.Infrastructure.Persistence;

#nullable disable

namespace UMBRAL_Back_end.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523082920_HU4_AddAutoReleaseRules")]
    partial class HU4_AddAutoReleaseRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.Clue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double?>("RadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StageId", "Order")
                        .IsUnique();

                    b.ToTable("Clues", (string)null);
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxDuration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Missions", (string)null);
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.MissionStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AutoReleaseMaxAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("AutoReleaseTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("BaseScore")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("QrCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Question")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("\"QrCode\" IS NOT NULL");

                    b.ToTable("MissionStages", (string)null);
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.TriviaOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("TriviaOptions", (string)null);
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.Clue", b =>
                {
                    b.HasOne("UMBRAL_Back_end.Domain.Missions.MissionStage", null)
                        .WithMany("Clues")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.MissionStage", b =>
                {
                    b.HasOne("UMBRAL_Back_end.Domain.Missions.Mission", null)
                        .WithMany("Stages")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.TriviaOption", b =>
                {
                    b.HasOne("UMBRAL_Back_end.Domain.Missions.MissionStage", null)
                        .WithMany("Options")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.Mission", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("UMBRAL_Back_end.Domain.Missions.MissionStage", b =>
                {
                    b.Navigation("Clues");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
